@startuml
hide footbox

title AskChoiceForm
actor       TestTaker as taker
participant singleForm [
    =AskSingleChoiceForm
    ----
    ====Knows
    ----
    * choices
    * selectedChoice (String)
    ----
    ====Collaborates
    ----
    * Question
]
control     QuizController  as ctrl
participant session [
    =QuizSession
    ----
    ====Knows
    ----
    * question
    * correct responses
    * incorrect responses
    * grade
    ----
    ====Collaborates
    ----
    * Quiz
]

participant question [
    =Question
    ----
    ====Knows
    * isCorrectAnswer
    * choices
    ----
    ====Collaborates
    * SingleChoice
]

participant singlechoice [
    =SingleChoice
    ----
    ====Knows
    * isCorrect
    ----
    ====Collaborates
    * Choice
]

participant choice [
    =Choice
    ----
    ====Knows
    ----
    * text
    * isCorrect
]

taker -> singleForm
note left
single-choice.html
--
radio button
--
value="1"
name="selectedChoice"
id="1"
end note
singleForm -> ctrl : POST /quiz
note left
selectedChoice=1
end note
ctrl -> session : respondWith(int indexOfChoice)
session -> session : question.choices().get(indexOfChoice)
session -> question : isCorrect(Choice... choices)
question -> singlechoice : isCorrect()
singlechoice -> choice : isCorrect()
singlechoice <-- choice
question <-- singlechoice
session <-- question
session -> session : questions.next()
ctrl <-- session
@enduml