@startuml
title Ask Question

actor       TestCreator as taker
boundary    SpringMVC   as mvc
control     QuizController  as ctrl
participant QuizSession as session
entity "AskSingleChoiceQuestionForm \n <<Value Object>>" as form
entity "Question \n <<Value Object>>" as question
entity "MultipleChoice \n <<Value Object>>" as multiple
entity "SingleChoice \n <<Value Object>>" as single
entity "Choice \n <<Service>>" as choice

taker -> mvc : GET /quiz
mvc -> ctrl : askQuestion()
ctrl -> session : question()
ctrl <-- session
ctrl -> form : from()
form -> question : text()
form <-- question
form -> question : choices()
question -> multiple : choices()
question <-- multiple
question -> single : choices()
question <-- single
form <-- question
form -> choice : text()
form <-- choice
ctrl <-- form
mvc <-- ctrl
taker <-- mvc
@enduml