@startuml
map Question <<Value Object>> {
  **Responsibilities** => **Collaborators**
  Knows //how to find// correct answer => MultipleChoice
  Knows //how to find// all choices (possible answers) =>
  | \n Knows //how to find// all choices (possible answers) \n | |
}

map MultipleChoice <<Value Object>> {
    **Responsibilities** => **Collaborators**
    Knows correct answer -> BOOLEAN QUERY {OWNS} => Answer
    Knows all choices (possible answers) {OWNS} =>
}

map Answer <<Value Object>> {
    **Responsibilities** => **Collaborators**
    Knows text =>
}

map QuizSession <<Entity>> {
    **Responsibilities** => **Collaborators**
    Knows current question => Quiz
    Handles response ("answer") => Response
    Knows when finished => Question
    Keeps track of all responses =>
    Calculates grade =>
}

map Quiz <<Entity>> {
      **Responsibilities** => **Collaborators**
      Knows questions => QuizSession
      Creates QuizSessions => QuestionRepository
}

@enduml