@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml
' uncomment the following line and comment the first to use locally
' !include C4_Context.puml

LAYOUT_WITH_LEGEND()

title System Context diagram for Quiz

Person(customer, "Test Taker", "Person using tests for revision")
System(quiz_system, "Quiz system", "Allows customers to add and answer quizes relating to topic of interest")

System_Ext(mail_system, "E-mail system", "Sends emails with report of score and correct and incorrect questions")
System_Ext(database, "Database", "Stores all of the core questions user has to answer and past scores")

Rel(customer, quiz_system, "Uses")
Rel_Back(customer, mail_system, "Sends e-mails to")
Rel_Neighbor(quiz_system, mail_system, "Sends e-mails", "SMTP")
Rel(quiz_system, database, "Uses")
@enduml